DELETE http://localhost:3001/api/persons/2

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "nombre": "agus",
    "numero": "2323423"
}

###

get http://localhost:3001/api/notas

###

get http://localhost:3001/api/notas/2

###

post http://localhost:3001/api/notas
Content-Type: application/json

{
    "contenido": "sample",
    "importancia": true
}

###