DELETE https://desolate-lowlands-97249.herokuapp.com/api/persons/2

###

//DELETE http://localhost:3001/api/persons/2

###

//POST http://localhost:3001/api/persons
post https://desolate-lowlands-97249.herokuapp.com/api/persons
Content-Type: application/json

{
    "nombre": "agus",
    "numero": "2323423"
}